model_opts:
  model: SAMBranch
  apply_class_weights: True
  generator: True
  obs_input_type: [ # scene_video_with_segmentation_v0,
                    # scene_video_with_ped_overlays_combined,
                   scene_graph,
                   box, speed]
  frameworks:
    pytorch: True
    hugging_faces: True
    multi-gpu: False
  process_input_features:
    enabled: True
    indexes_to_stack: [1, 2]
    static_features_indexes: []
exp_opts:
  datasets: [jaad_all]
  batch_size: [8]
  epochs: [60]
  lr: [5.0e-06]
