model_opts:
  model: TrajFusionNetGraphV2NoSpeed
  apply_class_weights: True
  generator: True
  obs_input_type: [scene_video_with_segmentation_v0,
                   scene_graph,
                   scene_context_with_ped_overlays, scene_context_with_ped_overlays_previous,
                   box]
  frameworks:
    pytorch: True
    hugging_faces: True
    multi-gpu: False
  process_input_features:
    enabled: True
    indexes_to_stack: []
    static_features_indexes: []
exp_opts:
  datasets: [combined]
  batch_size: [16]
  epochs: [30]
  lr: [5.0e-06]
