model_opts:
  model: TrajFusionNetGraphV1
  apply_class_weights: True
  generator: True
  obs_input_type: [scene_context_with_segmentation_v0, scene_context_with_segmentation_v5,
                   scene_graph, scene_graph_doubled,
                   scene_context_with_ped_overlays_combined, scene_context_with_ped_overlays_previous,
                   scene_context_non_static,
                   box, veh_speed]
  frameworks:
    pytorch: True
    hugging_faces: True
    multi-gpu: False
  process_input_features:
    enabled: True
    indexes_to_stack: [7, 8]
    static_features_indexes: []
exp_opts:
  datasets: [jaad_all]
  batch_size: [16]
  epochs: [30]
  lr: [5.0e-06]
