model_opts:
  model: VANSequentialV2
  apply_class_weights: True
  generator: True
  obs_input_type: [scene_video_with_segmentation_v0,
                   scene_video_with_ped_overlays_combined,
                   scene_graph,
                   scene_context_with_segmentation_v4_with_ped_overlays_combined,
                   scene_video_with_segmentation_v4_with_ped_overlays_combined,
                   box]
  frameworks:
    pytorch: True
    hugging_faces: True
    multi-gpu: False
  process_input_features:
    enabled: True
    indexes_to_stack: []
    static_features_indexes: []
exp_opts:
  datasets: [combined]
  batch_size: [16]
  epochs: [10]
  lr: [5.0e-06]
